"""Add email integration

Revision ID: 7c1f2610f483
Revises: e91d7f8dcc2a
Create Date: 2026-02-14 18:55:33.341225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1f2610f483'
down_revision: Union[str, None] = 'e91d7f8dcc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('email_message_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('email_subject', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_messages_email_message_id'), 'messages', ['email_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_email_message_id'), table_name='messages')
    op.drop_column('messages', 'email_sent')
    op.drop_column('messages', 'email_subject')
    op.drop_column('messages', 'email_message_id')
    # ### end Alembic commands ###
