"""Add email automation tables

Revision ID: e91d7f8dcc2a
Revises: 
Create Date: 2026-02-13 20:17:46.147558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91d7f8dcc2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workspace_email', 'contacts', ['workspace_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_email', 'contacts', type_='unique')
    # ### end Alembic commands ###
